## Code flow
----------------------------------

1. Load the dataset
2. Basic preprocessing V
3. Training Process

                    1.   Create the mode
                    2.   Forward pass
                    3.   Loss calculation
                    4.   Backprop
                    5.   Parameters update


4. Model evaluation

In [44]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [45]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [46]:
df.shape

(569, 33)

In [47]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [48]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

## Train Test split

In [49]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

## Scaling - so that all the values should come in same level

In [50]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [51]:
X_train

array([[ 1.47185762,  1.62312869,  1.48992142, ...,  0.97753329,
         1.22543531,  1.54214525],
       [ 1.19804103,  0.26959551,  1.19641787, ...,  0.55735717,
         0.26561893, -0.30306272],
       [ 0.40511379,  3.25242416,  0.48952903, ...,  1.3274254 ,
         0.96862825,  1.98604738],
       ...,
       [-0.81279963,  0.09724408, -0.84983928, ..., -1.3170867 ,
        -0.56418888, -0.44006955],
       [ 1.11817785, -0.58756558,  1.06000072, ...,  0.595555  ,
        -0.10675131, -0.10467683],
       [ 1.24082487, -0.2037964 ,  1.20881943, ...,  0.75904171,
         1.26235133,  0.08932484]])

In [52]:
y_train

33     M
516    M
259    M
390    B
84     B
      ..
496    B
338    B
522    B
444    M
85     M
Name: diagnosis, Length: 455, dtype: object

## Label Encoder - as M and B (above) cant be understandable by the tranformer so we need to convert M and B into 0 and 1

In [53]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder. transform(y_test)

In [54]:
y_train

array([1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1,
       0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0,
       0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0,
       1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,

## Converting the above Numpy array into Pytorch tensors

In [55]:
X_train_tensor = torch.from_numpy(X_train).float()
X_test_tensor = torch.from_numpy(X_test).float()
y_train_tensor = torch.from_numpy(y_train).float()
y_test_tensor = torch.from_numpy(y_test).float()

In [56]:
X_train_tensor

tensor([[ 1.4719,  1.6231,  1.4899,  ...,  0.9775,  1.2254,  1.5421],
        [ 1.1980,  0.2696,  1.1964,  ...,  0.5574,  0.2656, -0.3031],
        [ 0.4051,  3.2524,  0.4895,  ...,  1.3274,  0.9686,  1.9860],
        ...,
        [-0.8128,  0.0972, -0.8498,  ..., -1.3171, -0.5642, -0.4401],
        [ 1.1182, -0.5876,  1.0600,  ...,  0.5956, -0.1068, -0.1047],
        [ 1.2408, -0.2038,  1.2088,  ...,  0.7590,  1.2624,  0.0893]])

In [57]:
y_train_tensor

tensor([1., 1., 1., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 1., 0., 0., 1., 1.,
        0., 0., 1., 1., 0., 1., 1., 0., 1., 1., 0., 0., 1., 1., 1., 1., 1., 0.,
        0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 1., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0.,
        0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 1., 1., 1., 1., 0., 0., 0.,
        0., 1., 1., 0., 1., 0., 1., 1., 0., 1., 0., 1., 0., 1., 1., 1., 0., 1.,
        1., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 1., 0., 0., 1., 1.,
        0., 0., 1., 1., 0., 0., 0., 1., 1., 1., 0., 1., 0., 1., 0., 0., 0., 1.,
        0., 0., 0., 1., 0., 1., 0., 0., 0., 1., 1., 0., 0., 1., 1., 0., 1., 0.,
        0., 1., 0., 1., 1., 1., 0., 1., 0., 0., 1., 1., 1., 0., 1., 0., 1., 0.,
        1., 1., 1., 0., 0., 1., 0., 1., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
        0., 0., 0., 1., 1., 1., 0., 1., 

## Defining the model ( creating the structure of the model)

In [58]:
import torch.nn as nn

class MySimpleNN(nn.Module):

    def __init__(self, num_features):

        super().__init__()
        self.linear = nn.Linear(num_features, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, features):

        out = self.linear(features)
        out = self.sigmoid(out)
        return out


## Important parameters

In [59]:
learning_rate = 0.1
epochs = 25

In [60]:
loss_function = nn.BCELoss()  #this is binary cross entropy loss function

## Training pipeline

In [61]:
# create model
model = MySimpleNN(X_train_tensor.shape[1])
model.linear.weight

# define optimizer
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

# define loop
for epoch in range(epochs):

      # forward pass
      y_pred = model(X_train_tensor)

      # loss calculate
      loss = loss_function(y_pred, y_train_tensor.view(-1, 1))
      print(f'Epoch: {epoch+1} Loss: {loss}')

      # zero gradients ( clear gradients)
      optimizer.zero_grad()

      # backward propogation ( using autograd)
      loss.backward()

      #parameters update
      optimizer.step()

      # print loss in each epoch
      print(f'Epoch: {epoch+1} Loss: {loss}')


Epoch: 1 Loss: 0.6028083562850952
Epoch: 1 Loss: 0.6028083562850952
Epoch: 2 Loss: 0.5009582042694092
Epoch: 2 Loss: 0.5009582042694092
Epoch: 3 Loss: 0.4360627233982086
Epoch: 3 Loss: 0.4360627233982086
Epoch: 4 Loss: 0.39049816131591797
Epoch: 4 Loss: 0.39049816131591797
Epoch: 5 Loss: 0.3563779592514038
Epoch: 5 Loss: 0.3563779592514038
Epoch: 6 Loss: 0.32966381311416626
Epoch: 6 Loss: 0.32966381311416626
Epoch: 7 Loss: 0.30806073546409607
Epoch: 7 Loss: 0.30806073546409607
Epoch: 8 Loss: 0.29015734791755676
Epoch: 8 Loss: 0.29015734791755676
Epoch: 9 Loss: 0.27503159642219543
Epoch: 9 Loss: 0.27503159642219543
Epoch: 10 Loss: 0.2620520293712616
Epoch: 10 Loss: 0.2620520293712616
Epoch: 11 Loss: 0.25076982378959656
Epoch: 11 Loss: 0.25076982378959656
Epoch: 12 Loss: 0.2408563643693924
Epoch: 12 Loss: 0.2408563643693924
Epoch: 13 Loss: 0.23206491768360138
Epoch: 13 Loss: 0.23206491768360138
Epoch: 14 Loss: 0.22420646250247955
Epoch: 14 Loss: 0.22420646250247955
Epoch: 15 Loss: 0.2171

In [62]:
model.linear.weight

Parameter containing:
tensor([[ 0.3757,  0.2353,  0.1280,  0.2512,  0.1103,  0.0644,  0.2392,  0.3528,
         -0.0927, -0.0171,  0.2252, -0.0424,  0.2912,  0.1998,  0.0065,  0.0902,
          0.0255,  0.0140, -0.1493, -0.0083,  0.2409,  0.2229,  0.2045,  0.1064,
          0.2747,  0.1134,  0.1720,  0.1860,  0.3020, -0.0562]],
       requires_grad=True)

In [63]:
model.linear.bias

Parameter containing:
tensor([-0.1932], requires_grad=True)

## Model Evaluation

In [64]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.5).float()  # means if value is above 0.5 we call it 1 and if less than 0.5 we will call it 0
  accuracy = (y_pred == y_test_tensor). float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.5369344353675842


## The torch.optim module


torch.optim is a module in PyTorch that provides a variety of optimization
algorithms used to update the parameters of your model during training.

It includes common optimizers like Stochastic Gradient Descent (SGD), Adam,
RMSprop, and more.

It handles weight updates efficiently, including additional features like learning
rate scheduling and weight decay (regularization).

The model.parameters() method in PyTorch retrieves an iterator over all the
trainable parameters (weights and biases) in a model. These parameters are
instances of torch.nn.Parameter and include:

. Weights: The weight matrices of layers like nn.Linear, nn.Conv2d, etc.

. Biases: The bias terms of layers (if they exist).

The optimizer uses these parameters to compute gradients and update them
during training.