## Improvements

1. Building the neural network using nn module
2. Using built-in activation function
3. Using built-in loss function
4. Using built-in optimizer

The nn module
------------------------------------
The torch.nn module in PyTorch is a core library that provides a wide array of classes and functions designed to help developers build neural networks efficiently and effectively. It abstracts the complexity of creating and training neural networks by offering pre-built layers,loss functions, activation functions, and other utilities, enabling you to focus on designing and experimenting with model architectures.

Key Components of torch.nn:

1. Modules (Layers):

o nn.Module: The base class for all neural network modules. Your custom models and layers should subclass this class.

o Common Layers: Includes layers like nn.Linear (fully connected layer), nn.Conv2d (convolutional layer), nn.LSTM (recurrent layer), and many others.

2. Activation Functions:

o Functions like nn.ReLU, nn.Sigmoid, and nn.Tanh introduce non-linearities to the model, allowing it to learn complex patterns.

3. Loss Functions:
Provides loss functions such as nn.CrossEntropyLoss, nn.MSELoss, and nn.NLLLoss to quantify the difference between the model's predictions and the actual targets.

4. Container Modules:

o nn.Sequential: A sequential container to stack layers in order.

5. Regularization and Dropout:

Layers like nn.Dropout and nn.BatchNorm2d help prevent overfitting and improve
the model's ability to generalize to new data.



In [1]:
# create model class
import torch
import torch.nn as nn

class Model(nn.Module):

  def __init__(self, num_features):

      super().__init__()
      #self.linear1 = nn.Linear(num_features, 3)
      #self.relu = nn.ReLU()
      #self.linear2 = nn.Linear(3, 1)
      #self.sigmoid = nn.Sigmoid()

      self.network = nn.Sequential(
        nn.Linear(num_features, 3),
        nn.ReLU(),
        nn.Linear(3, 1),
        nn.Sigmoid()
      )

  def forward(self, features):

      #out = self.linear1(features)
      #out = self.relu(out)
      #out = self.linear2(out)
      #out = self.sigmoid(out)

      out = self.network(features)
      return out

In [2]:
# create dataset
features = torch.rand(10,5)

# create model
model = Model(features.shape[1])

# call model for forward pass
# model.forward(features)
model(features)

tensor([[0.4208],
        [0.4208],
        [0.4208],
        [0.4208],
        [0.4208],
        [0.4208],
        [0.4208],
        [0.4208],
        [0.4208],
        [0.4208]], grad_fn=<SigmoidBackward0>)

In [4]:
# show model weights
# model.linear1.weight
model.network[0].weight

Parameter containing:
tensor([[-0.2190, -0.0327, -0.1098,  0.2138, -0.4188],
        [-0.2841,  0.1153,  0.3383, -0.2595,  0.1328],
        [-0.2340,  0.3608, -0.2634, -0.3850, -0.1789]], requires_grad=True)

In [6]:
# show model weights
#model.linear2.weight
model.network[2].weight

Parameter containing:
tensor([[ 0.3095, -0.0596,  0.5285]], requires_grad=True)

In [7]:
# show model bias
# model.linear1.bias
model.network[0].bias

Parameter containing:
tensor([-0.4430, -0.1831, -0.2917], requires_grad=True)

In [8]:
# show model bias
# model.linear2.bias
model.network[2].bias

Parameter containing:
tensor([-0.3194], requires_grad=True)

In [9]:
!pip install torchinfo

In [10]:
from torchinfo import summary

summary(model, input_size=(10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Sequential: 1-1                        [10, 1]                   --
│    └─Linear: 2-1                       [10, 3]                   18
│    └─ReLU: 2-2                         [10, 3]                   --
│    └─Linear: 2-3                       [10, 1]                   4
│    └─Sigmoid: 2-4                      [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00