In [2]:
import torch
print(torch.__version__)

2.6.0+cu124


In [3]:
if torch.cuda.is_available():
    print("GPU is available!")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("GPU not available. Using CPU.")

GPU is available!
Using GPU: Tesla T4


## Creating a Tensor

In [4]:
# using empty ( to create a tensor using torch- here values are already stored in memory , it will show)
a = torch.empty(2,3)

In [5]:
# check type
type(a)

torch.Tensor

In [6]:
# using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [7]:
# using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [8]:
# using rand
torch.rand(2,3)

tensor([[0.8083, 0.5296, 0.2595],
        [0.9935, 0.3804, 0.8681]])

In [9]:
# use of seed ( it means it will give random values between 0 and 1 - but it we run it again , it will give some other value. So to keep the random values fixed , we will use manual_seed)
torch.rand(2,3)

tensor([[0.7075, 0.4944, 0.2407],
        [0.6255, 0.7876, 0.4367]])

In [10]:
# manual_seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [11]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [12]:
# using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [13]:
# other ways

# arange ( range from 1 to 10 here)
print("using arange ",torch.arange(1,10))

# arange with step of 2
print("using arange with step ",torch.arange(1,10,2))

# using linspace ( 0 to 10 tak we created evenly space)
print("using linspace ",torch.linspace(0,10,10))

# using eye ( identity matrix where diagonal is 1 )
print("using eye ",torch.eye(5))

# using full ( we want 3*3 matrix where each value is 5)
print("using full ",torch.full((3,3),5))

using arange  tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
using arange with step  tensor([1, 3, 5, 7, 9])
using linspace  tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye  tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full  tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


## Tensor Shapes

In [14]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [15]:
# ( 2 rows 3 columns )
x.shape

torch.Size([2, 3])

In [16]:
# suppose we want to copy the shape of one tensor to another ( values will be different)
torch.empty_like(x)

tensor([[      202618688,       202616416,           65536],
        [      202639361, 132173323568229,               0]])

In [17]:
# create a tensor of (2,3) same as above x but now all values should be 0
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [18]:
# create a tensor of (2,3) same as above x but now all values should be 1
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [19]:
# create a tensor of (2,3) same as above x but now all values should be random
#torch.rand_like(x)
# this will throw an error as in x tensor we had all values as int but we know rand gives us random values between 0 and 1 so thats why we need to typecast it to float first

In [20]:
# to fix the above error we will to explicit write
torch.rand_like(x, dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

## Tensor Data Types

In [21]:
# find data type
x.dtype

torch.int64

In [22]:
# assign data type
torch.tensor([1.0,2.0,3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [23]:
torch.tensor([1,2,3], dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [24]:
# using to()
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |


## Mathematical operations

### 1. Scalar operation

In [25]:
x = torch.rand(2,2)
x

tensor([[0.7118, 0.7876],
        [0.4183, 0.9014]])

In [26]:
# addition
x + 2
# substraction
x - 2
# multiplication
x * 3
# division
x / 3
# int division
(x * 100)//3
# mod
((x * 100)//3)%2
# power
x**2

tensor([[0.5066, 0.6203],
        [0.1750, 0.8125]])

### 2. Element wise operation

In [27]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.9969, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.8238]])
tensor([[0.5557, 0.9770, 0.4440],
        [0.9478, 0.7445, 0.4892]])


In [28]:
# add
a + b
# sub
a - b
# multiply
a * b
# division
a / b
# power
a ** b
# mod
a % b

tensor([[0.4411, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.3346]])

In [29]:
c = torch.tensor([1, -2, 3, -4])

In [30]:
# abs
torch.abs(c)

tensor([1, 2, 3, 4])

In [31]:
# negative
torch.neg(c)

tensor([-1,  2, -3,  4])

In [32]:
d = torch.tensor([1.9, 2.3, 3.7, 4.4])

In [33]:
# round
torch.round(d)

tensor([2., 2., 4., 4.])

In [34]:
# ceil
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [35]:
# floor
torch.floor(d)

tensor([1., 2., 3., 4.])

In [36]:
# clamp
torch.clamp(d, min=2, max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

### 3. Reduction operation

In [37]:
e = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
e

tensor([[8., 0., 7.],
        [0., 0., 9.]])

In [38]:
# sum
torch.sum(e)
# sum along columns
torch.sum(e, dim=0)
# sum along rows
torch.sum(e, dim=1)

tensor([15.,  9.])

In [39]:
# mean
torch.mean(e)
# mean along col
torch.mean(e, dim=0)

tensor([4., 0., 8.])

In [40]:
# median
torch.median(e)

tensor(0.)

In [41]:
# max and min
torch.max(e)
torch.min(e)

tensor(0.)

In [42]:
# product
torch.prod(e)

tensor(0.)

In [43]:
# standard deviation
torch.std(e)

tensor(4.4272)

In [44]:
# variance
torch.var(e)

tensor(19.6000)

In [45]:
# argmax
torch.argmax(e)

tensor(5)

In [46]:
# argmin
torch.argmin(e)

tensor(1)

### 4. Matrix operations

In [47]:
f = torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(3,2), low=0, high=10)

print(f)
print(g)

tensor([[5, 7, 3],
        [9, 4, 0]])
tensor([[5, 7],
        [5, 9],
        [9, 7]])


In [48]:
# matrix multiplcation
torch.matmul(f, g)

tensor([[ 87, 119],
        [ 65,  99]])

In [49]:
vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])

# dot product
torch.dot(vector1, vector2)

tensor(11)

In [50]:
# transpose
torch.transpose(f, 0, 1)

tensor([[5, 9],
        [7, 4],
        [3, 0]])

In [51]:
h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
h

tensor([[5., 9., 8.],
        [9., 7., 9.],
        [2., 6., 7.]])

In [52]:
# determinant
torch.det(h)

tensor(-110.)

In [53]:
# inverse
torch.inverse(h)

tensor([[ 0.0455,  0.1364, -0.2273],
        [ 0.4091, -0.1727, -0.2455],
        [-0.3636,  0.1091,  0.4182]])

### 5. Comparison operations

In [54]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)

print(i)
print(j)

tensor([[7, 8, 3],
        [6, 1, 5]])
tensor([[5, 0, 4],
        [3, 8, 8]])


In [55]:
# greater than
i > j
# less than
i < j
# equal to
i == j
# not equal to
i != j
# greater than equal to

# less than equal to

tensor([[True, True, True],
        [True, True, True]])

### 6. Special functions

In [56]:
k = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
k

tensor([[3., 3., 5.],
        [0., 6., 4.]])

In [57]:
# log
torch.log(k)

tensor([[1.0986, 1.0986, 1.6094],
        [  -inf, 1.7918, 1.3863]])

In [58]:
# exp
torch.exp(k)

tensor([[ 20.0855,  20.0855, 148.4132],
        [  1.0000, 403.4288,  54.5981]])

In [59]:
# sqrt
torch.sqrt(k)

tensor([[1.7321, 1.7321, 2.2361],
        [0.0000, 2.4495, 2.0000]])

In [60]:
# sigmoid
torch.sigmoid(k)

tensor([[0.9526, 0.9526, 0.9933],
        [0.5000, 0.9975, 0.9820]])

In [61]:
# softmax
torch.softmax(k, dim=0)

tensor([[0.9526, 0.0474, 0.7311],
        [0.0474, 0.9526, 0.2689]])

In [62]:
# relu
torch.relu(k)

tensor([[3., 3., 5.],
        [0., 6., 4.]])

## Inplace Operations

In [63]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.6574, 0.3451, 0.0453],
        [0.9798, 0.5548, 0.6868]])
tensor([[0.4920, 0.0748, 0.9605],
        [0.3271, 0.0103, 0.9516]])


In [64]:
m.add_(n)

tensor([[1.1494, 0.4199, 1.0058],
        [1.3069, 0.5650, 1.6384]])

In [65]:
m

tensor([[1.1494, 0.4199, 1.0058],
        [1.3069, 0.5650, 1.6384]])

In [66]:
n

tensor([[0.4920, 0.0748, 0.9605],
        [0.3271, 0.0103, 0.9516]])

In [67]:
torch.relu(m)

tensor([[1.1494, 0.4199, 1.0058],
        [1.3069, 0.5650, 1.6384]])

In [68]:
m.relu_()

tensor([[1.1494, 0.4199, 1.0058],
        [1.3069, 0.5650, 1.6384]])

In [69]:
m

tensor([[1.1494, 0.4199, 1.0058],
        [1.3069, 0.5650, 1.6384]])

## Copying a Tensor

In [70]:
a = torch.rand(2,3)
a

tensor([[0.2855, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])

In [71]:
b = a

In [72]:
b

tensor([[0.2855, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])

In [73]:
a[0][0] = 0

In [74]:
a

tensor([[0.0000, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])

In [75]:
b

tensor([[0.0000, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])

In [76]:
id(a)

132173655749072

In [77]:
id(b)

132173655749072

In [78]:
b = a.clone()

In [79]:
a

tensor([[0.0000, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])

In [80]:
b

tensor([[0.0000, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])

In [81]:
a[0][0] = 10

In [82]:
a

tensor([[10.0000,  0.2324,  0.9141],
        [ 0.7668,  0.1659,  0.4393]])

In [83]:
b

tensor([[0.0000, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])

In [84]:
id(a)

132173655749072

In [85]:
id(b)

132173655572560

# Till now we have worked on CPU , now we will check and use CPU

In [86]:
torch.cuda.is_available()

True

In [88]:
device1 = torch.device('cuda')

In [89]:
# creating a new tensor in GPU
torch.rand((2,3),device=device1)

tensor([[0.3563, 0.0303, 0.7088],
        [0.2009, 0.0224, 0.9896]], device='cuda:0')

In [90]:
# moving an existing tensor on GPU
a = torch.rand((2,3))
b = a.to(device1)

tensor([[0.2243, 0.8935, 0.0497],
        [0.1780, 0.3011, 0.1893]], device='cuda:0')

In [94]:
b+5 # this operation is now performed on GPU and not CPU

tensor([[5.0000, 5.2324, 5.9141],
        [5.7668, 5.1659, 5.4393]])

In [97]:
import time

# Define the size of the matrices
size = 10000 # Large size for performance comparison

# Create random matrices on CPU
matrix_cpu1 = torch.randn(size, size)
matrix_cpu2 = torch.randn(size, size)

# Measure time on CPU
start_time = time.time()
result_cpu = torch.matmul(matrix_cpu1, matrix_cpu2) # Matrix multiplication on CPU
cpu_time = time.time() - start_time

print(f"Time on CPU: {cpu_time:.4f} seconds")

# Move matrices to GPU
matrix_gpu1 = matrix_cpu1.to('cuda')
matrix_gpu2 = matrix_cpu2.to('cuda')

# Measure time on GPU
start_time = time.time()
result_gpu = torch.matmul(matrix_gpu1, matrix_gpu2) # Matrix multiplication on GPU
torch.cuda.synchronize() # Ensure all GPU operations are complete
gpu_time = time.time() - start_time

print(f"Time on GPU: {gpu_time:.4f} seconds")

# Compare results
print("\nSpeedup (CPU time / GPU time):", cpu_time / gpu_time)

Time on CPU: 15.0342 seconds
Time on GPU: 0.7039 seconds

Speedup (CPU time / GPU time): 21.358407722596215


# Reshaping Tensors

In [98]:
a = torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [100]:
# reshape
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [102]:
# flatten
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [103]:
b = torch.rand(2,3,4)
b

tensor([[[0.0175, 0.1639, 0.4733, 0.1569],
         [0.3070, 0.1020, 0.1914, 0.9407],
         [0.5304, 0.5252, 0.6272, 0.6186]],

        [[0.8889, 0.1310, 0.2608, 0.3661],
         [0.9643, 0.2575, 0.0298, 0.6887],
         [0.2672, 0.4914, 0.4353, 0.3025]]])

In [105]:
# permute
b.permute(2,0,1).shape  # means at the top cell it is 2,3,4 now it become 4,2,3

torch.Size([4, 2, 3])

In [106]:
# unsqueeze -> This function is used to add a dimension of size one to a tensor at a specific position.
c = torch.rand(255,255,3)
c.unsqueeze(0).shape

torch.Size([1, 255, 255, 3])

In [109]:
# squeeze
d = torch.rand(255,255,3)
d.squeeze(0)


tensor([[[0.4412, 0.6365, 0.2340],
         [0.9822, 0.4782, 0.0272],
         [0.5600, 0.3241, 0.4774],
         ...,
         [0.0727, 0.2634, 0.2862],
         [0.1469, 0.6082, 0.0864],
         [0.8306, 0.4435, 0.8529]],

        [[0.0776, 0.1845, 0.9087],
         [0.4379, 0.6001, 0.0735],
         [0.1917, 0.1842, 0.6745],
         ...,
         [0.6140, 0.4891, 0.0938],
         [0.9959, 0.4909, 0.8943],
         [0.7290, 0.7968, 0.8405]],

        [[0.7215, 0.5320, 0.3423],
         [0.7886, 0.9037, 0.8246],
         [0.1985, 0.4719, 0.2841],
         ...,
         [0.7678, 0.4471, 0.8237],
         [0.6441, 0.8935, 0.2071],
         [0.5005, 0.1689, 0.6380]],

        ...,

        [[0.4287, 0.7000, 0.0066],
         [0.2173, 0.6946, 0.3978],
         [0.6087, 0.3158, 0.0173],
         ...,
         [0.3143, 0.8508, 0.1206],
         [0.9290, 0.4181, 0.9507],
         [0.7158, 0.6938, 0.8322]],

        [[0.9224, 0.9773, 0.3112],
         [0.4077, 0.5333, 0.7169],
         [0.

In [110]:
d.squeeze(0).shape

torch.Size([255, 255, 3])

# Coverting Pytorch to Numpy

In [111]:
import numpy as np

In [112]:
a = torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [113]:
b = a.numpy()
b

array([1, 2, 3])

In [115]:
type(b)

numpy.ndarray

# Coverting Numpy to Pytorch

In [116]:
c = np.array([1,2,3])
c

array([1, 2, 3])

In [117]:
torch.from_numpy(c)

tensor([1, 2, 3])